/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CustomerDataEntry;
import javax.swing.*;
import java.awt.*;
import javax.swing.text.DocumentFilter;
import javax.swing.text.*;
public class App {
    CardLayout crd;
    public String getGreeting() {
        return "Hello World!";
    }
    private JPanel createPanel(){
       
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        JLabel firstNameLabel = new JLabel("First Name");
        JButton subButton = new JButton("Submit Information");
        JTextArea firstNameArea = new JTextArea(1, 1);
        DefaultStyledDocument doc = new DefaultStyledDocument();
        DocumentFilter filter = new DocumentFilter();
        
       
        
        firstNameArea.setDocument(doc);
       
        firstNameArea.setBorder(BorderFactory.createLineBorder(Color.black));
        JLabel lastNameLabel = new JLabel("Last Name");
        JLabel zipCodeLabel = new JLabel("Zip Code");
        firstNameArea.setLineWrap(true);
        JTextArea lastNameArea = new JTextArea(1,1);
        lastNameArea.setLineWrap(true);
        JTextArea zipCodeArea = new JTextArea(1,1);
        lastNameArea.setBorder(BorderFactory.createLineBorder(Color.black));
        zipCodeArea.setLineWrap(true);
        zipCodeArea.setBorder(BorderFactory.createLineBorder(Color.black));
        panel.add(firstNameLabel);
        panel.add(firstNameArea);
        panel.add(lastNameLabel);
        panel.add(lastNameArea);
        panel.add(zipCodeLabel);
        panel.add(zipCodeArea);
        panel.add(subButton);
        return panel;
    }
    public void createForm(){
        
        JFrame form = new JFrame();
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        form.setContentPane(createPanel());
        
        form.pack();
        form.setPreferredSize(new Dimension(800, 500));
        form.setLocation(500, 200);
        
        form.setVisible(true);
        
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        new App().createForm();
    }
}
